# Generated by Django 4.1.7 on 2023-02-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_alter_image_options_remove_image_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='asl_letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
