# Generated by Django 4.1.7 on 2023-02-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_image_asl_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='deleted_at',
        ),
    ]
